repos:
  - repo: local
    hooks:
      - id: isort
        name: "Sort imports"
        language: system
        types: [file, python]
        entry: isort
      - id: black
        name: "Black formatting"
        language: system
        types: [file, python]
        entry: "black"
        args: [--safe, "--line-length=79"]
      - id: flake8
        name: "Flake8 linting"
        language: system
        types: [file, python]
        entry: flake8

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=Google, -i]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
      - id: uv-lock
      - id: uv-export